Make 'addr' more useful
- Print single interface
- Print all IPs
- Print IPv4 or IPv6
- Optional long output and sorted output

Closes #17

diff --git a/addr b/addr
--- a/addr
+++ b/addr
@@ -15,37 +15,85 @@
 #
 # Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
 #
-# abstract: show IPv4 address for interface <if> or all interfaces
+# abstract: list bound IP addresses
 #
-# Usage: addr [<if>]
+# Documentation {{{1
 #
+VERSION='1.0'
 
-ip_cmd='ip address show'
-ifconfig_cmd='ifconfig'
+print_help() {
+    cat <<END >&2
+Usage: $0 [OPTION] [INTERFACE]
 
-if command -v iip >/dev/null; then
-    cmd="$ip_cmd"
-elif command -v ifconfig >/dev/null; then
-    cmd="$ifconfig_cmd"
-else
-    printf "I don't know how to list your IP addresses.\n" >&2
+List bound IP addresses
+
+  -a	    include 127.* addresses
+  -l	    prepend address with the interface it is bound to
+  -4	    print IPv4 addresses (default)
+  -6	    print IPv6 addresses
+  -s        sort output
+  -h   	    display this help and exit
+  -v        output version information and exit
+END
+}
+
+print_version() {
+    cat <<END >&2
+$0 $VERSION
+Copyright (C) 2014 Orion Arts
+License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
+This is free software: you are free to change and redistribute it.
+There is NO WARRANTY, to the extent permitted by law.
+
+Written by Jeremy Brubaker.
+END
+}
+
+# Process options {{{1
+#
+all='n'
+long='n'
+sort='n'
+v4='y'
+v6='n'
+while getopts ':alshv46' c; do
+    case $c in
+        a) all='y' ;;
+        l) long='y' ;;
+        4) v4='y'; v6='n' ;;
+        6) v6='y'; v4='n' ;;
+        s) sort='y' ;;
+        h) print_help; exit 0 ;;
+        v) print_version; exit 0 ;;
+        ?) printf "Invalid option: -%s\n" "$OPTARG" >&2; print_help; exit 1 ;;
+    esac
+done
+shift $((OPTIND-1))
+
+# Easy way to not ignore 127.* addresses if we ask for such an interface
+# explicitly
+[ -n "$1" ] && all='y'
+
+# Main {{{1
+#
+if ! command -v ip >/dev/null 2>/dev/null; then
+    printf "ip(8) not found. Exiting\n" >&2
     exit 1
 fi
 
-if [ -n "$1" ]; then
-    $cmd $1 |
-        awk '/inet / {print gensub("/.*$", "", 1, $2)}'
-else
-    if [ "$cmd" = "$ip_cmd" ]; then
-        $cmd | awk '
-        /^[[:digit:]]+:/ {iface = $2}
-        /inet / {printf("%s %s\n", iface, gensub("/.*$", "", 1, $2))}
-        ' | grep -v 'lo:' | sort
-    elif [ "$cmd" = "$ifconfig_cmd" ]; then
-        $cmd | awk '
-        /^[[:alpha:]]/ {iface = $1}
-        /inet / {printf("%s %s\n", iface, $2)}
-        ' | grep -v 'lo:' | sort
-    fi
-fi
+[ "$v4" = 'y' ] && inet="inet"
+[ "$v6" = 'y' ] && inet="inet6"
+
+addrs=$(ip address show $1 | awk ' \
+    /^[[:digit:]]+:/ {iface = gensub(":", "", 1, $2)} \
+    /'$inet' /       {printf("%s\t%s\t%s\n", iface, gensub("/.*$", "", 1, $2), gensub("^[^/]*", "", 1, $2))}')
+
+[ "$all" != 'y' ]  && addrs=$(echo "$addrs" | grep -Ev '\s127')
+[ "$long" = 'n' ]  && addrs=$(echo "$addrs" | sed 's@^.*\s\(.*\)\s.*$@\1@')
+
+# Pipe through sort if needed, otherwise tee just passes it on
+echo "$addrs" |
+if [ "$sort" = 'y' ]; then sort
+else tee
+fi | column --table --separator "	"
 
