Rename 'anypinentry' to 'pinentry-any'

diff --git a/dmenu-pinentry b/dmenu-pinentry
--- a/dmenu-pinentry
+++ b/dmenu-pinentry
@@ -37,10 +37,10 @@ else
     exit 1
 fi
 
-if ! command -v anypinentry >/dev/null; then
-    printf "anypinentry not found\n" >&2
+if ! command -v pinentry-any >/dev/null; then
+    printf "pinentry-any not found\n" >&2
     exit 1
 fi
 
-anypinentry "$@" --prompt "dmenu $(make_dmenu_args) -c -P -p \"\$AP_PROMPT\""
+pinentry-any "$@" --prompt "dmenu $(make_dmenu_args) -c -P -p \"\$AP_PROMPT\""
 
