Add option for horizontal layout
Closes #5

diff --git a/dmenu-menu b/dmenu-menu
--- a/dmenu-menu
+++ b/dmenu-menu
@@ -49,6 +49,7 @@ Usage: $0 [OPTION] [INTERFACE]
 
 Present a menu based on commands in a config file
 
+  -h        display menu horizontally instead of vertically
   -h   	    display this help and exit
   -v        output version information and exit
 
@@ -78,7 +79,7 @@ END
 # Process options {{{1
 #
 MENUDIR="${XDG_CONFIG_DIR:-$HOME/.config}/dmenu-menu"
-
+layout=v
 case ${1-} in
     -h | --help)     print_help; exit 0 ;;
          --version)  print_version; exit 0 ;;
@@ -92,6 +93,7 @@ case ${1-} in
             exit 1
         fi
         ;;
+    -H | --horizontal) layout=h; shift ;;
     -*) print_help "Invalid option: $1"; exit 1 ;;
     '') printf "%s: No menu file given.\n" "$0"; exit 1 ;;
 esac
@@ -156,7 +158,12 @@ done < "$MENUFILE"
 
 # Main {{{1
 #
-choice=$(echo -e "$choices" | dmenu $(make_dmenu_args) -c -i -p "${prompt-}" -l "${#COMMANDS[*]}" "$@")
+case $layout in
+    v) layout="-c -l ${#COMMANDS[*]}" ;;
+    h) layout= ;;
+    *) printf "%s: layout '%s' is invalid.\n" "$0" "$layout"; exit 1 ;;
+esac
+choice=$(echo -e "$choices" | dmenu $(make_dmenu_args) -i -p "${prompt-}" $layout "$@")
 
 if [ -n "$choice" ]; then
     ${COMMANDS[$choice]}
