Get 'passmenu' from upstream

diff --git a/passmenu b/passmenu
--- a/passmenu
+++ b/passmenu
@@ -1,30 +1,22 @@
 #!/usr/bin/env bash
-#
-# `passmenu` is a dmenu-based interface to pass, the standard Unix
-# password manager. This design allows you to quickly copy a password to the
-# clipboard without having to open up a terminal window if you don't already
-# have one open.
-#
-# If `--type` is specified, the password is typed using xdotool
-# instead of copied to the clipboard.
-#
-# Usage
-#
-#     passmenu [--type] [dmenu arguments...]
-#
-# [dmenu]: http://tools.suckless.org/dmenu/
-# [xdotool]: http://www.semicomplete.com/projects/xdotool/
-# [pass]: http://www.zx2c4.com/projects/password-store/
-#
-# https://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu
-#
 
 shopt -s nullglob globstar
 
 typeit=0
 if [[ $1 == "--type" ]]; then
-    typeit=1
-    shift
+	typeit=1
+	shift
+fi
+
+if [[ -n $WAYLAND_DISPLAY ]]; then
+	dmenu=dmenu-wl
+	xdotool="ydotool type --file -"
+elif [[ -n $DISPLAY ]]; then
+	dmenu=dmenu
+	xdotool="xdotool type --clearmodifiers --file -"
+else
+	echo "Error: No Wayland or X11 display detected" >&2
+	exit 1
 fi
 
 prefix=${PASSWORD_STORE_DIR-~/.password-store}
@@ -32,13 +24,12 @@ password_files=( "$prefix"/**/*.gpg )
 password_files=( "${password_files[@]#"$prefix"/}" )
 password_files=( "${password_files[@]%.gpg}" )
 
-password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")
+password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")
 
 [[ -n $password ]] || exit
 
 if [[ $typeit -eq 0 ]]; then
-    pass show -c "$password" 2>/dev/null
+	pass show -c "$password" 2>/dev/null
 else
-    pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
-        xdotool type --clearmodifiers --file -
+	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
 fi
