Check for required binaries

diff --git a/pct-enter b/pct-enter
--- a/pct-enter
+++ b/pct-enter
@@ -21,6 +21,14 @@
 #
 # NOTE: the remote user must have passwordless sudo permissions
 #
+for b in jq \
+    ; do
+    if ! command -v "$b" >/dev/null 2>&1; then
+        printf "'%s' not found\n" "$b" >&2
+        exit 1
+    fi
+done
+
 if [ -z "$1" ]; then
     printf '%s\n' 'No container requested' >&2
     exit 1
