Pingsweep arbitrary subnets. Bump to v2.0
Closes #45

diff --git a/pingsweep b/pingsweep
--- a/pingsweep
+++ b/pingsweep
@@ -19,15 +19,16 @@
 #
 # Documentation {{{1
 #
-VERSION='1.0'
+VERSION='2.0'
 
 print_help() {
     cat <<END >&2
-Usage: $0 [OPTION] <network address>
+Usage: $0 [OPTION] <ip/cidr>
 
-Ping all addresses in a /24 network
+Ping all addresses in a subnet
 
-  -p        ping hosts in parellel and send output to a file
+  -p        ping hosts in parellel
+  -C        do not use color
   -h   	    display this help and exit
   -v        output version information and exit
 END
@@ -47,9 +48,12 @@ END
 
 # Process options {{{1
 #
+COLOR='[1;32m'
+RESET='[0m'
 bg='n'
-while getopts ':phv' c; do
+while getopts ':Cphv' c; do
     case $c in
+        C) COLOR= ; RESET= ;;
         p) bg='y' ;;
         h) print_help; exit 0 ;;
         v) print_version; exit 0 ;;
@@ -57,18 +61,109 @@ while getopts ':phv' c; do
     esac
 done
 shift $((OPTIND-1))
+OPTIND=1
 
-# 4th octet is stripped off
-net=$(echo "$1" | sed 's/\(.*\..*\..*\)\..*/\1/')
+# Functions {{{1
+#
+# isip {{{2
+#
+# @description Check if a string is a valid IP Address
+#   Currently support IPv4 only
+#
+# @arg $1 str String to validate
+#
+# @exitcode 0 if $1 is a valid IP address
+# @exitcode 1 if $1 is not a valid IP address
+#
+isip() {(
+    octet="(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])"
+    printf -- %s "$1" | grep -qE "^$octet\.$octet\.$octet\.$octet$"
+)}
 
-if ! echo "$net" | grep -E '[0-9]+\.[0-9]+\.[0-9]+' >/dev/null 2>&1; then
-    printf "%s: missing network address (x.x.x[.x])\n" "$0" >&2
-    print_help
+# iscidr {{{2
+#
+# @description Check if a string is a valid IPv4 CIDR
+#
+# @arg $1 str String to validate
+#
+# @exitcode 0 if $1 is a valid IPv4 CIDR
+# @exitcode 1 if $1 is not a valid IPv4 CIDR
+#
+iscidr() { printf %s "$1" | grep -qE "^([0-9]|[12][0-9]|3[012])$"; }
+
+# dec2ip {{{2
+#
+# @description Convert a 32-bit decimal number to an IPv address
+#
+# @arg $1 32-bit integer
+#
+# @sdout Dotted quad IPv4 address
+#
+dec2ip() {
+    printf '%d.%d.%d.%d' \
+        "$(($1 >> 24 & 0xff))" \
+        "$(($1 >> 16 & 0xff))" \
+        "$(($1 >> 8  & 0xff))" \
+        "$(($1 >> 0  & 0xff))"
+}
+
+# ip2dec {{{2
+#
+# @description Convert an IPv4 address to a 32-bit integer
+#
+# @arg $1 str IPv address
+#
+# @stdout 32-bit integer
+#
+ip2dec() {
+    s=0
+    oldifs=$IFS; IFS=.
+    for o in $1; do s=$((s * 256 + o)); done
+    IFS=$oldifs
+    echo "$s"
+}
+
+# cidr2mask {{{2
+#
+# @description Convert an IPv4 CIDR to a subnet mask
+#
+# @arg $1 int CIDR
+#
+# @stdout Subnet mask
+#
+cidr2mask() {(
+    full_octets=$(($1/8))
+    partial_octet=$(($1%8))
+	mask=
+	for octet in $(seq 0 3); do
+        if [ $octet -lt "$full_octets" ]; then
+            mask="${mask}255"
+        elif [ $octet -eq "$full_octets" ]; then
+			mask="$mask$(echo "256 - 2^(8-$partial_octet)" | bc)"
+        else
+            mask="${mask}0"
+        fi
+
+        [ $octet -lt 3 ] && mask="$mask."
+    done
+
+    echo $mask
+)}
+
+
+# Main {{{1
+#
+# Extract address and CIDR
+ip=$(echo $1 | sed 's@/.*$@@')
+cidr=$(echo $1 | sed 's@^.*/@@')
+
+# Validate input
+if ! isip "$ip" || ! iscidr "$cidr"; then
+    printf "%s: invalid network address: '%s'\n" "$0" "$1" >&2
     exit 1
 fi
 
-# Print header {{{1
-#
+# Print header
 if [ "$bg" = 'y' ]; then
     tmpfile=$(mktemp "$(basename "$0").XXXXXX")
     trap 'rm -f "$tmpfile"' EXIT
@@ -76,23 +171,46 @@ if [ "$bg" = 'y' ]; then
     printf "# pingsweep of %s.0/24...\n" "$net" >>"$tmpfile"
     printf "# start: %s\n" "$(date)" >>"$tmpfile"
 else
-    printf "\033[1;32mBeginning pingsweep of %s.0/24...\033[0m\n\n" "$net"
+    printf "\033[1;32mBeginning pingsweep of %s/$s...\033[0m\n\n" "$ip" "$cidr"
 fi
 
-# Ping the network {{{1
+# Ping the network {{{2
 #
-for host in $(seq 1 254); do
+IPMSK=0xffffffff
+
+# Get network address and mask as integers
+net=$(ip2dec $ip)
+msk=$(ip2dec "$(cidr2mask "$cidr")")
+net=$((net & msk))
+
+# Get the first and last IP on the network
+# /31 and /32 are special cases
+if [ "$cidr" -eq 32 ]; then
+    first=$net
+    last=$net
+elif [ "$cidr" -eq 31 ]; then
+    first=$net
+    last=$((net + 1))
+else
+    first=$((net + 1))
+    last=$((net + (IPMSK ^ msk) - 1))
+fi
+
+# ^C kills the whole sweep
+trap 'exit' INT
+
+# Run the sweep
+for host in $(seq "$first" "$last"); do
     if [ "$bg" = 'y' ]; then
         {
-            if ping -c1 "$net.$host" >/dev/null 2>&1; then
-                printf "%s.%s\n" "$net" "$host" >>"$tmpfile"
-            fi
+            ping -c1 "$host" >/dev/null 2>&1 &&
+                printf "%s\n" "$(dec2ip "$host")" >>"$tmpfile"
         } &
     else
-       printf "trying %s.%s..." "$net" "$host"
-       if ping -c1 "$net.$host" >/dev/null 2>&1; then
-           printf "\033[1;32malive\033[0m"
-       fi
+        printf "trying %s..." "$(dec2ip "$host")"
+        if ping -c1 "$$host" >/dev/null 2>&1; then
+            printf "${COLOR}alive${RESET}"
+        fi
        echo
     fi
 done
