Pass shellcheck and do some formatting

diff --git a/pingsweep b/pingsweep
--- a/pingsweep
+++ b/pingsweep
@@ -67,7 +67,7 @@ shift $((OPTIND-1))
 net=$(echo "$1" | sed 's/\(.*\..*\..*\)\..*/\1/')
 
 if ! echo "$net" | grep -E '[0-9]+\.[0-9]+\.[0-9]+' >/dev/null 2>&1; then
-    printf "$0: missing network address (x.x.x[.x])\n" >&2
+    printf "%s: missing network address (x.x.x[.x])\n" "$0" >&2
     print_help
     exit 1
 fi
@@ -75,13 +75,13 @@ fi
 # Print header {{{1
 #
 if [ "$bg" = 'y' ]; then
-    tmpfile=$(mktemp "$(basename $0).XXXXXX")
+    tmpfile=$(mktemp "$(basename "$0").XXXXXX")
     trap 'rm -f "$tmpfile"' EXIT
 
-    printf "# pingsweep of $net.0/24...\n" >>"$tmpfile"
-    printf "# start: $(date)\n" >>"$tmpfile"
+    printf "# pingsweep of %s.0/24...\n" "$net" >>"$tmpfile"
+    printf "# start: %s\n" "$(date)" >>"$tmpfile"
 else
-    printf "\033[1;32mBeginning pingsweep of $net.0/24...\033[0m\n\n"
+    printf "\033[1;32mBeginning pingsweep of %s.0/24...\033[0m\n\n" "$net"
 fi
 
 # Ping the network {{{1
@@ -90,11 +90,11 @@ for host in $(seq 1 254); do
     if [ "$bg" = 'y' ]; then
         {
             if ping -c1 "$net.$host" >/dev/null 2>&1; then
-                printf "$net.$host\n" >>"$tmpfile"
+                printf "%s.%s\n" "$net" "$host" >>"$tmpfile"
             fi
         } &
     else
-       printf "trying $net.$host..."
+       printf "trying %s.%s..." "$net" "$host"
        if ping -c1 "$net.$host" >/dev/null 2>&1; then
            printf "\033[1;32malive\033[0m"
        fi
@@ -119,6 +119,6 @@ if [ "$bg" = 'y' ]; then
                  for (i in ips)
                     print ips[i] | "sort -t. -k4 -n" }'
 
-    printf "# end: $(date)\n"
+    printf "# end: %s\n" "$(date)"
 fi
 
