Improve pingsweep
Closes #30

- Argument checking
- Use ping return code
- Optionally background the pings
- Output to stdout only

diff --git a/pingsweep b/pingsweep
--- a/pingsweep
+++ b/pingsweep
@@ -22,23 +22,103 @@
 # abstract:	hasty pingsweep script when nmap is not available
 ################################################################################
 
-NETWORK=$1
+# Documentation {{{1
+#
+VERSION='1.0'
 
-printf "\033[1;32mBeginning pingsweep of $NETWORK.0 ...\033[0m\n\n"
-printf "# pingsweep of $NETWORK.0 ... "  > $NETWORK.0.sweep
-printf "# start: $(date)"               >> $NETWORK.0.sweep
+print_help() {
+    cat <<END >&2
+Usage: $0 [OPTION] <network address>
 
-for HOST in $(seq 1 254) ; do 
-    printf "trying $NETWORK.$HOST..."
+Ping all addresses in a /24 network
 
-	ISALIVE=$(ping -c 1 $NETWORK.$HOST | grep received | cut -d " " -f 4) 
+  -p        ping hosts in parellel and send output to a file
+  -h   	    display this help and exit
+  -v        output version information and exit
+END
+}
 
-	if [ $ISALIVE = "1" ] ; then
-		printf "\033[1;32malive\033[0m"
-		printf "$NETWORK.$HOST" >> $NETWORK.0.sweep ;
-	fi ;
-    echo
+print_version() {
+    cat <<END >&2
+$0 $VERSION
+Copyright (C) 2014 Orion Arts
+License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
+This is free software: you are free to change and redistribute it.
+There is NO WARRANTY, to the extent permitted by law.
+
+Written by Jeremy Brubaker.
+END
+}
+
+# Process options {{{1
+#
+bg='n'
+while getopts ':phv' c; do
+    case $c in
+        p) bg='y' ;;
+        h) print_help; exit 0 ;;
+        v) print_version; exit 0 ;;
+        ?) printf "Invalid option: -%s\n" "$OPTARG" >&2; print_help; exit 1 ;;
+    esac
+done
+shift $((OPTIND-1))
+
+# 4th octet is stripped off
+net=$(echo "$1" | sed 's/\(.*\..*\..*\)\..*/\1/')
+
+if ! echo "$net" | grep -E '[0-9]+\.[0-9]+\.[0-9]+' >/dev/null 2>&1; then
+    printf "$0: missing network address (x.x.x[.x])\n" >&2
+    print_help
+    exit 1
+fi
+
+# Print header {{{1
+#
+if [ "$bg" = 'y' ]; then
+    tmpfile=$(mktemp "$(basename $0).XXXXXX")
+    trap 'rm -f "$tmpfile"' EXIT
+
+    printf "# pingsweep of $net.0/24...\n" >>"$tmpfile"
+    printf "# start: $(date)\n" >>"$tmpfile"
+else
+    printf "\033[1;32mBeginning pingsweep of $net.0/24...\033[0m\n\n"
+fi
+
+# Ping the network {{{1
+#
+for host in $(seq 1 254); do
+    if [ "$bg" = 'y' ]; then
+        {
+            if ping -c1 "$net.$host" >/dev/null 2>&1; then
+                printf "$net.$host\n" >>"$tmpfile"
+            fi
+        } &
+    else
+       printf "trying $net.$HOST..."
+       if ping -c1 "$net.$host" >/dev/null 2>&1; then
+           printf "\033[1;32malive\033[0m"
+       fi
+       echo
+    fi
 done
 
-echo "# end: $(date)" >> $NETWORK.0.sweep
+# Output background scan {{{1
+#
+if [ "$bg" = 'y' ]; then
+    wait # for all the backgrounded pings
+
+    # Use awk to sort the list of alive IPs because they may be printed in any
+    # order due to the backgrounding
+    < "$tmpfile" awk '
+    /^# ping/  { header[1] = $0 }
+    /^# start/ { header[2] = $0 }
+    /^[^#]/    { ips[i] = $0
+                 i++ }
+    END        { print header[1]
+                 print header[2]
+                 for (i in ips)
+                    print ips[i] | "sort -t. -k4 -n" }'
+
+    printf "# end: $(date)\n"
+fi
 
