Change screenshot to use scrot

diff --git a/screenshot b/screenshot
--- a/screenshot
+++ b/screenshot
@@ -17,44 +17,29 @@
 #
 # abstract: take a screenshot
 #
+shotdir=$XDG_CACHE_HOME/screenshot
 
-DIR="$HOME/var/lib/screenshot"
-LOGDIR="$HOME/var/log"
+mkdir -p "$shotdir"
 
-mkdir -p "$DIR"
-mkdir -p "$LOGDIR"
+date="$(date +%Y%m%d@%H%M%S)"
+name="${shotdir}/screenshot-${date}.png"
 
-DATE="$(date +%Y%m%d@%H%M%S)"
-NAME="${DIR}/screenshot-${DATE}.png"
-LOG="${DIR}/screenshot.log"
-
-# Check for GraphicsMagick
-if command -v gm; then
-    IMPORT="gm import"
-elif command -v import; then
-    IMPORT="import"
-else
-    printf "GraphicsMagic or ImageMagick required but not found.\n" >&2
+# Check for scrot
+if ! command -v scrot >/dev/null; then
+    printf '%s\n' 'scrot not found.'>&2
+    exit 1
 fi
 
-# Check if the dir to store screenshots exists
-if [ ! -d "$DIR" ]; then mkdir -p "$DIR"; fi
-
-# Screenshot a selected window
-if [ "$1" = "win" ]; then $IMPORT "$NAME"; fi
-
-# Screenshot the entire screen
-if [ "$1" = "scr" ]; then $IMPORT -window root "$NAME"; fi
-
-# Screenshot a selected area
-if [ "$1" = "area" ]; then $IMPORT "$NAME"; fi
-
-if [ $# = 0 ]; then
-    # Display a warning if no area defined
-    echo "No screenshot area has been specified. Screenshot not taken."
-    echo "${DATE}: No screenshot area has been defined. Screenshot not taken." >> "$LOG"
-else
-    # Save the screenshot in the directory and edit yhe log
-    echo "$NAME" >> "$LOG"
+if [ "$1" = '-d' ]; then
+    args='-d 3'
+    shift
 fi
+
+case $1 in
+    area)     args="$args -bs" ;;
+    current)  args="$args -bu" ;;
+    screen|*) args="$args" ;;
+esac
+
+scrot $args -e 'xclip -selection clipboard -t image/png -i $f' "$name"
 
